language: android

jdk:
  - oraclejdk8

android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by the project
    - build-tools-23.0.2

    # The SDK version used to compile the project
    - android-23

    # Repositories for Gradle and Maven
    - extra-android-m2repository
    #- extra-google-m2repository

    # Additional components
    - extra-android-support
    - extra-google-google_play_services

  # Licenses are automatically accepted by Travis CI
  licenses:
    #- 'android-sdk-license-.+'
    #- 'google-gdk-license-.+'

script:
  - ./gradlew clean build connectedCheck -PdisablePreDex

notifications:
  email: true

sudo: false

cache:
  directories:
    - $HOME/.gradle
